---
title: "Tidy Tuesday (2025-03-04)"
author: "Scarlett"
---

```{r}
library(tidyverse)
library(lubridate)
```


# data 
```{r}

longbeach <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-03-04/longbeach.csv')

head(longbeach)

colnames(longbeach)

```

 
Which type of pets are adopted most often?
```{r}
adoptions_by_sex <- longbeach %>%
  filter(outcome_type == "adoption") %>%
  group_by(animal_type, sex) %>%
  summarise(adoptions = n(), .groups = "drop")

ggplot(adoptions_by_sex, aes(x = animal_type, y = adoptions, fill = sex)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(
    title = "Adoptions by Animal Type and Sex",
    x = "Animal Type",
    y = "Number of Adoptions",
    fill = "Sex",
    caption = "Data: TidyTuesday 2025-03-04"
  ) +
  theme_classic()


```
- This grouped bar plot shows that dogs and cats are the most frequently adopted animals, with dogs slightly leading. In addition, within each species, the distribution of adoptions by sex appears relatively balanced, except that there may be a slight preference for females among cats.
